module.exports = {
    "extends": "eslint:recommended",
    "rules": {
        //
        // enabled over eslint:recommended
        //
        "array-bracket-spacing": ["error", "never"],
        "array-callback-return": "error",
        "block-spacing": "error",
        "brace-style": ["error", "1tbs", { "allowSingleLine": false }],
        "camelcase": "error",
        "comma-dangle": ["error", "never"],
        "comma-spacing": "error",
        "comma-style": ["error", "last"],
        "computed-property-spacing": "error",
        "consistent-return": "error",
        "consistent-this": ["error", "that"],
        "curly": "error",
        "dot-notation": "error",
        "eol-last": "error",
        "eqeqeq": "error",
        "func-call-spacing": "error",
        "guard-for-in": "error",
        "indent": ["error", 4, { "SwitchCase": 1 }],
        "keyword-spacing": "error",
        "key-spacing": ["error",
            { "beforeColon": false, "afterColon": true, "mode": "minimum" }
        ],
        "linebreak-style": ["error", "unix"],
        "lines-around-comment": ["error",
            { "allowBlockStart": true, "allowObjectStart": true, "ignorePattern": "BEGIN_|END_|SOASTA PRIVATE" }
        ],
        "max-len": ["warn", 120, 4],
        "new-cap": "error",
        "new-parens": "error",
        "newline-after-var": ["error", "always"],
        "newline-before-return": "error",
        "no-alert": "error",
        "no-array-constructor": "error",
        "no-caller": "error",
        "no-catch-shadow": "error",
        "no-confusing-arrow": "error",
        "no-debugger": "error",
        "no-div-regex": "error",
        "no-empty": "error",
        "no-empty-function": "error",
        "no-eq-null": "error",
        "no-eval": "error",
        "no-extend-native": "error",
        "no-extra-bind": "error",
        "no-extra-label": "error",
        "no-extra-parens": ["error", "functions"],
        "no-floating-decimal": "error",
        "no-global-assign": "error",
        "no-implicit-globals": "error",
        "no-implied-eval": "error",
        "no-inline-comments": "error",
        "no-irregular-whitespace": "error",
        "no-iterator": "error",
        "no-label-var": "error",
        "no-labels": "error",
        "no-lone-blocks": "error",
        "no-lonely-if": "error",
        "no-loop-func": "error",
        "no-mixed-requires": "error",
        "no-mixed-spaces-and-tabs": "error",
        "no-multi-spaces": ["error",
            { "exceptions": { "VariableDeclarator": true, "Property": true } }
        ],
        "no-multi-str": "error",
        "no-multiple-empty-lines": ["error", { "max": 1 }],
        "no-nested-ternary": "error",
        "no-new": "error",
        "no-new-func": "error",
        "no-new-object": "error",
        "no-new-require": "error",
        "no-new-symbol": "error",
        "no-new-wrappers": "error",
        "no-octal-escape": "error",
        "no-path-concat": "error",
        "no-process-exit": "error",
        "no-proto": "error",
        "no-return-assign": "error",
        "no-script-url": "error",
        "no-self-assign": "error",
        "no-self-compare": "error",
        "no-sequences": "error",
        "no-shadow": "error",
        "no-shadow-restricted-names": "error",
        "no-trailing-spaces": ["error",
            {"skipBlankLines": false }
        ],
        "no-undef-init": "error",
        "no-underscore-dangle": "error",
        "no-unused-expressions": "error",
        "no-unused-labels": "error",
        "no-use-before-define": ["error", { "functions": false, "classes": true }],
        "no-useless-constructor": "error",
        "no-void": "error",
        "no-whitespace-before-property": "error",
        "no-with": "error",
        "object-curly-spacing": ["error", "always"],
        "one-var-declaration-per-line": "error",
        "operator-linebreak": ["error", "after"],
        "padded-blocks": ["error", "never"],
        "padding-line-between-statements": ["error",
            { "blankLine": "always", "prev": "block-like", "next": "if" },
            { "blankLine": "always", "prev": "expression", "next": "if" },
            { "blankLine": "always", "prev": "var", "next": "if" },
            { "blankLine": "always", "prev": "block-like", "next": "var" },
            { "blankLine": "always", "prev": "try", "next": "*" },
            { "blankLine": "always", "prev": "block-like", "next": "expression" },
            { "blankLine": "always", "prev": "*", "next": "function" },
            { "blankLine": "always", "prev": "*", "next": "block" },
            { "blankLine": "always", "prev": "block", "next": "*" },
            { "blankLine": "always", "prev": "*", "next": "block-like" },
            { "blankLine": "always", "prev": "block-like", "next": "*" },
            { "blankLine": "always", "prev": "*", "next": "return" }
        ],
        "quotes": ["error", "double", { "avoidEscape": true }],
        "radix": "error",
        "semi": "error",
        "semi-spacing": ["error",
            { "before": false, "after": true }
        ],
        "space-before-blocks": "error",
        "space-before-function-paren": ["error", "never"],
        "space-in-parens": ["error", "never"],
        "space-infix-ops": "error",
        "space-unary-ops": ["error", { "words": true, "nonwords": false }],
        "spaced-comment": "error",
        "strict": ["error", "function"],
        "valid-jsdoc": ["warn", { "requireReturn": false, "prefer": { "return": "returns" } }],
        "wrap-iife": "error",
        "yoda": "error"
    }
};